global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
rule_files:
  - 'alert.rules'
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
    scheme: http
    timeout: 10s
    api_version: v2

scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090

- job_name: node
  scrape_interval: 5s
  static_configs:
  - targets: ['node-exporter:9100']

- job_name: 'blackbox'
  metrics_path: /metrics
  params:
    module: [http_2xx]
  static_configs:
    - targets:
      - blackbox:9115

- job_name: 'blackbox-http'
  metrics_path: /probe
  params:
    module: [http_2xx]
  static_configs:
    - targets:
      - wordpress:80
      - grafana:3000
  relabel_configs:
    - source_labels: [ __address__ ]
      target_label: __param_target
    - source_labels: [ __param_target ]
      target_label: instance
    - target_label: __address__
      replacement: "blackbox:9115"  # Blackbox exporter.

- job_name: wordpress_exporter
  honor_timestamps: true
  scrape_interval: 60s
  scrape_timeout: 15s
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets:
      - wordpress_exporter:8888

- job_name: 'mysql-exporter'
  metrics_path: /metrics
  static_configs:
    - targets:
      - mysql-exporter:9104

- job_name: 'cadvisor-exporter'
  scrape_interval: 1s
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets:
      - cadvisor-exporter:8080
